### ISSUE TITLE
a few missing 'f's

### ISSUE THREAD

**Issue by f00dikator** [MatthewDietrich/ServiceDesk-Plus-REST-API#1]
Hey there, just something small...but, you're missing a few of the 'f's in your format strings. 

egrep "[^f]\'[^\']*\{[a-zA-Z_]+\}[^\']*\'" sdpapi.py

**Comment by MatthewDietrich** [comment]
Thank you for letting me know, and thanks for the handy regex. I will fix this as soon as I can.
